### ISSUE TITLE
Requires ID

### ISSUE THREAD

**Issue by kmccullough** [kaxi1993/canvas-to-image#6]
The canvas I'm wanting to download is not visible, part of the document, nor does it have an ID. I should be able to pass in the canvas element itself, but the current implementation assumes you are passing an ID.

**Comment by kaxi1993** [comment]
@kmccullough  now you can pass canvas html element as a first parameter. Thanks for pointing this issue.

**Comment by kmccullough** [comment]
That fixed it so I could use your library and your library fixed the issue with IE/Edge that I came here to fix. Thanks!
