### ISSUE TITLE
Download doesn't trigger on Chrome and Safari on iOS.

### ISSUE THREAD

**Issue by sikandarchishty** [kaxi1993/canvas-to-image#8]
Hi, downlaod isn't triggering on Chrome and Safari on iOS but works fine on Web.

using:
React: 16.14.0
React DOM: 16.14.0

using following function on click

Code:
`const el = useRef(); // assigned to canvas
const exportAsImage = async (el) => {
  const canvas = await html2canvas(el, { scale: 2 });
  canvasToImage(canvas, options);
 };`

**Comment by kaxi1993** [comment]
@sikandarchishty I tested it on Chrome and Safari on iOS and seems like everything works fine.
you need to use `el.current` instead.

```
  const exportAsImage = async (el) => {
    const canvas = await html2canvas(el.current, { scale: 2 });
    canvasToImage(canvas, options);
  };
```
